from app_state_data.app_state_data_json import JSONAppStateDataService
from notification_services.telegram_notification_service import TelegramNotificationService

APP_STATE_SERVICE = JSONAppStateDataService

DEFAULT_EXCEL_FILE_PATH = 'product_ids.xlsx'

NOTIFICATION_SERVICE = TelegramNotificationService
